### ISSUE TITLE
Timout on serverles functions

### ISSUE THREAD

**Issue by jonashrem** [philippdormann/mensamax-api#22]
At the moment, I always get a timeout here. 

https://mensa.vercel.app/api/?p=PB2499&e=maxcluster&details=yes

the original link works https://mensahaus.de/mensamax/Wochenplan/WochenplanExtern/WochenPlanExternForm.aspx, so I assume timeout just needs to be increased.

**Comment by philippdormann** [comment]
timeout for serverless functions is 5 seconds for Hobby accounts 🤷‍♂️

You might have to self-host/use the library if your institutions plan is too slow to be processed

**Comment by jonashrem** [comment]
Thanks. I'll check that out
